version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
